### ISSUE TITLE
Docs: Logo broken in Pagy AI

### ISSUE THREAD

**Issue by brandonzylstra** [ddnexus/pagy#817]
### 👀 Before submitting...

- [x] I asked [Pagy AI](https://gurubase.io/g/pagy) (Good starting point for further investigation).
- [x] I searched through the [Documentation](https://ddnexus.github.io/pagy/), [Issues](https://github.com/ddnexus/pagy/issues), and [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### Description

<img width="180" height="91" alt="Image" src="https://github.com/user-attachments/assets/51096291-5950-4214-8cdc-0044b0b07d47" />

<img width="377" height="244" alt="Image" src="https://github.com/user-attachments/assets/5d319489-5225-4fc0-a7dd-9f6d9af9302e" />

**Comment by ddnexus** [comment]
It looks right from here.

The images that you posted look like a CSS download problem from your area. Please, clear the browser cache and try to reload the page.

If the problem persists, look at errors in the browser console log and post it.
Thanks

**Comment by ddnexus** [comment]
I just got the missing logo in the AI widget.
I don't find where is the other though.

**Comment by brandonzylstra** [comment]
The other one appears after you ask a question.

**Comment by ddnexus** [comment]
Thank you. I think all it's fixed now. Please, can you confirm?

**Comment by brandonzylstra** [comment]
Yes, it's working perfectly now

**Comment by brandonzylstra** [comment]
Actually, it's working on https://ddnexus.github.io/pagy/ but it's still broken on http://127.0.0.1:8000/pagy

I assume that's because I didn't pull directly from GitHub, and the latest release was 5 days ago but the push to GitHub pages was 11 hours ago.

**Comment by ddnexus** [comment]
Yes, it's still broken for the apps. Thank you!

**Comment by everdone-app** [comment]
Hello @brandonzylstra, We're the team behind Everdone, the AI solution that enables developers to bypass the tedious manual work of documentation.

We saw your request concerning documentation and wanted to offer a practical, immediate solution. As a gesture of support for your project, we've documented 20 files from your repository using Everdone's engine.

This provides you with a ready-to-review documentation artifact right here: https://app.everdone.ai/services/codedoc/documentation/3e828da0-93d8-487c-a18d-adf5d856d42f/pagy/master

We hope this serves as a valuable resource! Your feedback on the generated documentation is welcome, and you can always get your entire repo covered with a free Everdone account.
